services:
  social-pg:
    image: bitnami/postgresql:latest
    ports:
      - "5437:5432"
    environment:
      POSTGRESQL_USERNAME: ${DATABASE_USER}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./docker:/docker-entrypoint-initdb.d:ro
      - social_pg_data:/bitnami/postgresql

volumes:
  social_pg_data: