"""add_approved_for_social

Revision ID: 3c7243af0979
Revises: c8c00c8cdcb7
Create Date: 2026-04-04 10:58:08.347977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7243af0979'
down_revision: Union[str, Sequence[str], None] = 'c8c00c8cdcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_profiles', sa.Column('approved_for_social', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('team_profiles', sa.Column('approved_for_social', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_profiles', 'approved_for_social')
    op.drop_column('organization_profiles', 'approved_for_social')
    # ### end Alembic commands ###
