services:
  competitions-pg:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./docker:/docker-entrypoint-initdb.d:ro
      - competitions_pg_data:/bitnami/postgresql

volumes:
  competitions_pg_data: