spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

logging:
  level:
    root: WARN
    br.com.athloshub.social_service: INFO
    feign: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
