"""Package de exceções específicas de domínio para Clean Architecture."""

from auth_service.core.exceptions.auth import (
    AuthenticationError,
    InvalidCallbackError,
    InvalidCredentialsError,
    InvalidTokenError,
    KeycloakCommunicationError,
    RefreshTokenError,
    TokenExpiredError,
)
from auth_service.core.exceptions.membership import (
    CannotRemoveOwnerError,
    CannotRemoveSelfError,
    InviteNotFoundError,
    InviteRequiredError,
    JoinPolicyViolationError,
    JoinRequestNotFoundError,
    MembershipAlreadyExistsError,
    MembershipNotFoundError,
    MustBeActiveMemberError,
    NotActiveMemberError,
    NotMemberError,
    OwnerCannotLeaveError,
)
from auth_service.core.exceptions.organization import (
    AlreadyOwnerError,
    NewOwnerNotActiveMemberError,
    NotOwnerError,
    NotOwnerOrOrganizerError,
    OrganizationAccessDeniedError,
    OrganizationAlreadyExists,
    OrganizationAlreadyExistsError,
    OrganizationInactiveError,
    OrganizationNotFoundError,
    OrganizationStatusConflictError,
    OrganizerAlreadyExistsError,
    OrganizerNotFoundError,
    OwnerNotNeedOrganizerError,
)
from auth_service.core.exceptions.user import (
    AvatarUploadError,
    EmailAlreadyInUseError,
    EmailAlreadyVerifiedError,
    IdentityConflictError,
    NotAdminError,
    RegistrationError,
    UserActivationError,
    UserAlreadyExistsError,
    UserDisabledError,
    UsernameAlreadyInUseError,
    UserNotActivatedError,
    UserNotFoundError,
)

__all__ = [
    # User exceptions
    "UserNotFoundError",
    "UserAlreadyExistsError",
    "UsernameAlreadyInUseError",
    "EmailAlreadyInUseError",
    "EmailAlreadyVerifiedError",
    "UserNotActivatedError",
    "UserDisabledError",
    "UserActivationError",
    "RegistrationError",
    "AvatarUploadError",
    "IdentityConflictError",
    "NotAdminError",
    # Organization exceptions
    "OrganizationNotFoundError",
    "OrganizationAlreadyExistsError",
    "OrganizationAlreadyExists",
    "OrganizationAccessDeniedError",
    "OrganizationInactiveError",
    "OrganizationStatusConflictError",
    "OrganizerAlreadyExistsError",
    "OrganizerNotFoundError",
    "OwnerNotNeedOrganizerError",
    "NotOwnerError",
    "NotOwnerOrOrganizerError",
    "AlreadyOwnerError",
    "NewOwnerNotActiveMemberError",
    # Membership exceptions
    "MembershipNotFoundError",
    "MembershipAlreadyExistsError",
    "InviteNotFoundError",
    "JoinRequestNotFoundError",
    "CannotRemoveOwnerError",
    "CannotRemoveSelfError",
    "OwnerCannotLeaveError",
    "NotActiveMemberError",
    "NotMemberError",
    "MustBeActiveMemberError",
    "JoinPolicyViolationError",
    "InviteRequiredError",
    # Auth exceptions
    "AuthenticationError",
    "InvalidCredentialsError",
    "InvalidTokenError",
    "TokenExpiredError",
    "KeycloakCommunicationError",
    "InvalidCallbackError",
    "RefreshTokenError",
]
