"""dedupe_auth_teams_unique_constraint

Revision ID: 2479a94992d0
Revises: 9b3c4d5e6f7a
Create Date: 2026-04-05 15:28:34.585093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2479a94992d0'
down_revision: Union[str, Sequence[str], None] = '9b3c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_rulesets_organization_slug'), table_name='sport_rulesets')
    op.create_foreign_key('fk_team_captain_id', 'teams', 'players', ['team_captain'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_team_captain_id', 'teams', type_='foreignkey')
    op.create_index(op.f('ix_sport_rulesets_organization_slug'), 'sport_rulesets', ['organization_slug'], unique=False)
    # ### end Alembic commands ###
