"""add stats

Revision ID: 57d61f7e0186
Revises: 87e024897c1c
Create Date: 2026-02-03 09:30:57.358483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d61f7e0186'
down_revision: Union[str, Sequence[str], None] = '87e024897c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id')
    )
    op.create_table('stats_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('stats_ruleset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stats_ruleset_id'], ['stats_rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('stats_type_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['stats_type_id'], ['stats_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('competitions', sa.Column('current_phase', sa.String(), nullable=True))
    op.drop_index(op.f('ix_modalities_org_code'), table_name='modalities')
    op.create_index(op.f('ix_modalities_organization_slug'), 'modalities', ['organization_slug'], unique=False)
    op.drop_index(op.f('ix_teams_org_code'), table_name='teams')
    op.create_index(op.f('ix_teams_organization_slug'), 'teams', ['organization_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_organization_slug'), table_name='teams')
    op.create_index(op.f('ix_teams_org_code'), 'teams', ['organization_slug'], unique=False)
    op.drop_index(op.f('ix_modalities_organization_slug'), table_name='modalities')
    op.create_index(op.f('ix_modalities_org_code'), 'modalities', ['organization_slug'], unique=False)
    op.drop_column('competitions', 'current_phase')
    op.drop_table('player_stats')
    op.drop_table('stats_types')
    op.drop_table('stats_rulesets')
    # ### end Alembic commands ###
