"""create initial tables

Revision ID: 6d5521cb28f3
Revises: 
Create Date: 2025-12-04 16:18:31.151566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5521cb28f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalities_org_code'), 'modalities', ['org_code'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('min_members_per_team', sa.Integer(), nullable=False),
    sa.Column('max_members_per_team', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=False),
    sa.Column('segments_regular_number', sa.Integer(), nullable=False),
    sa.Column('overtime_segments', sa.Integer(), nullable=False),
    sa.Column('penalty_segments', sa.Integer(), nullable=False),
    sa.Column('has_break_segments', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_rulesets')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_modalities_org_code'), table_name='modalities')
    op.drop_table('modalities')
    # ### end Alembic commands ###
