"""fix circular dependency

Revision ID: 71f2b64e09f1
Revises: 6d5521cb28f3
Create Date: 2025-12-18 14:28:48.390086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f2b64e09f1'
down_revision: Union[str, Sequence[str], None] = '6d5521cb28f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_code', sa.String(length=50), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('team_captain', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_captain'], ['players.id'], name='fk_team_captain_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_org_code'), 'teams', ['org_code'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('score_pro', sa.Integer(), nullable=False),
    sa.Column('score_against', sa.Integer(), nullable=False),
    sa.Column('score_balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('round_number_match', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=True),
    sa.Column('away_team_id', sa.UUID(), nullable=True),
    sa.Column('home_feeder_match_id', sa.UUID(), nullable=True),
    sa.Column('away_feeder_match_id', sa.UUID(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('has_penalties', sa.Boolean(), nullable=False),
    sa.Column('has_overtime', sa.Boolean(), nullable=False),
    sa.Column('winner_team_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['away_feeder_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['home_feeder_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('competitions', sa.Column('sport_ruleset_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'competitions', 'sport_rulesets', ['sport_ruleset_id'], ['id'])
    op.drop_constraint(op.f('sport_rulesets_competition_id_key'), 'sport_rulesets', type_='unique')
    op.drop_constraint(op.f('sport_rulesets_competition_id_fkey'), 'sport_rulesets', type_='foreignkey')
    op.drop_column('sport_rulesets', 'competition_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_rulesets', sa.Column('competition_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sport_rulesets_competition_id_fkey'), 'sport_rulesets', 'competitions', ['competition_id'], ['id'])
    op.create_unique_constraint(op.f('sport_rulesets_competition_id_key'), 'sport_rulesets', ['competition_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_column('competitions', 'sport_ruleset_id')
    op.drop_table('segments')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_teams_org_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('rounds')
    op.drop_table('groups')
    # ### end Alembic commands ###
