"""create_initial_models

Revision ID: bd705d9a82c5
Revises: 
Create Date: 2026-03-29 15:35:44.249852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd705d9a82c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalities_organization_slug'), 'modalities', ['organization_slug'], unique=False)
    op.create_table('sport_rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=False),
    sa.Column('segments_regular_number', sa.Integer(), nullable=False),
    sa.Column('overtime_segments', sa.Integer(), nullable=False),
    sa.Column('penalty_segments', sa.Integer(), nullable=False),
    sa.Column('has_break_segments', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sport_ruleset_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('min_members_per_team', sa.Integer(), nullable=False),
    sa.Column('max_members_per_team', sa.Integer(), nullable=False),
    sa.Column('teams_per_group', sa.Integer(), nullable=True),
    sa.Column('teams_qualified_per_group', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('current_phase', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.ForeignKeyConstraint(['sport_ruleset_id'], ['sport_rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats_rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_slug', sa.String(length=255), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('team_captain', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_captain'], ['players.id'], name='fk_team_captain_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_organization_slug'), 'teams', ['organization_slug'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('score_pro', sa.Integer(), nullable=False),
    sa.Column('score_against', sa.Integer(), nullable=False),
    sa.Column('score_balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('round_number_match', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=True),
    sa.Column('away_team_id', sa.UUID(), nullable=True),
    sa.Column('home_feeder_match_id', sa.UUID(), nullable=True),
    sa.Column('away_feeder_match_id', sa.UUID(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('has_penalties', sa.Boolean(), nullable=False),
    sa.Column('has_overtime', sa.Boolean(), nullable=False),
    sa.Column('winner_team_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['away_feeder_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['home_feeder_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('keycloak_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('stats_ruleset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stats_ruleset_id'], ['stats_rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invites_invite_token'), 'team_invites', ['invite_token'], unique=True)
    op.create_index('ix_team_invites_token_status', 'team_invites', ['invite_token', 'status'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('stats_type_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['stats_type_id'], ['stats_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'segment_number', name='uq_match_segment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('player_stats')
    op.drop_index('ix_team_invites_token_status', table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_invite_token'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_table('stats_types')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_teams_organization_slug'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('stats_rulesets')
    op.drop_table('rounds')
    op.drop_table('groups')
    op.drop_table('competitions')
    op.drop_table('sport_rulesets')
    op.drop_index(op.f('ix_modalities_organization_slug'), table_name='modalities')
    op.drop_table('modalities')
    # ### end Alembic commands ###
