"""initial_structure

Revision ID: c3b7e68d2bce
Revises: 0cfd2963bbda
Create Date: 2026-01-14 18:06:32.411331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b7e68d2bce'
down_revision: Union[str, Sequence[str], None] = '0cfd2963bbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_team_captain_id', 'teams', 'players', ['team_captain'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_team_captain_id', 'teams', type_='foreignkey')
    # ### end Alembic commands ###
