"""test

Revision ID: ffe0de2f9d11
Revises: c3b7e68d2bce
Create Date: 2026-01-23 19:22:42.203183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe0de2f9d11'
down_revision: Union[str, Sequence[str], None] = 'c3b7e68d2bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('current_phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'current_phase')
    # ### end Alembic commands ###
