export enum MatchEventType {
  GOAL = 'GOAL',
  FOUL = 'FOUL',
  YELLOW_CARD = 'YELLOW_CARD',
  RED_CARD = 'RED_CARD',
  SUBSTITUTION = 'SUBSTITUTION',
  PERIOD_START = 'PERIOD_START',
  PERIOD_END = 'PERIOD_END',
  PENALTY = 'PENALTY',
  OWN_GOAL = 'OWN_GOAL',
  VAR_REVIEW = 'VAR_REVIEW',
}
