export enum MatchEventType {
  SCORE = 'SCORE',
  PERIOD_START = 'PERIOD_START',
  PERIOD_END = 'PERIOD_END',
  TIMEOUT = 'TIMEOUT',
  SUBSTITUTION = 'SUBSTITUTION',
  FOUL = 'FOUL',
  WARNING = 'WARNING',
  EJECTION = 'EJECTION',
  REVIEW = 'REVIEW',
  INJURY = 'INJURY',
  CUSTOM = 'CUSTOM',
}
